name: Doxygen GitHub Pages
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Doxygen
      run: doxygen Doxyfile  # Or use separate doxygen action
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: documentation/html  # Your output
    - name: Deploy
      uses: actions/deploy-pages@v4